{{- if .Values.istioinjection.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "artemis.fullname" . }}
spec:
  hosts:
    - {{ .Values.istioinjection.hostname }}
  gateways:
  - {{ include "artemis.fullname" . }}
  tcp:
  - match:
    - port: 61616
    route:
    - destination:
        host: {{ include "artemis.fullname" . }}
        port:
          number: 61616
  http:
  - route:
    - destination:
        host: {{ include "artemis.fullname" . }}
        port:
          number: 8161
    headers:
      request:
        set:
          x-forwarded-proto: https

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "artemis.fullname" . }}
spec:
  selector:
    istio: {{ .Values.istioinjection.selector.istio }}
  servers:
  - hosts:
    - {{ .Values.istioinjection.hostname }}
    port:
      number: 80
      name: http
      protocol: HTTP
  - hosts:
    - {{ .Values.istioinjection.hostname }}
    port:
      number: 61616
      name: core
      protocol: TCP
{{- end }}
