{{- if .Values.certvalidator.configmaps.db }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    app.kubernetes.io/component: mosip
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
data:
  db_port: {{ .Values.certvalidator.configmaps.db.db_port | quote }}
  db_suuser: {{ .Values.certvalidator.configmaps.db.db_suuser | quote }}
  db_server: {{ .Values.certvalidator.configmaps.db.db_server | quote }}
  {{- end }}

  {{- if .Values.certvalidator.configmaps.preexpirydays }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pre-expirydays
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    app.kubernetes.io/component: mosip
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
data:
  pre-expirydays: {{ .Values.certvalidator.configmaps.preexpirydays | quote }}
  {{- end }}