kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{.Release.Name}}-{{ .Release.Namespace }}-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps", "secrets"]
    verbs: ["get","list","create", "update", "delete", "patch"]
