apiVersion: str()
kind: str(matches='Deployment|StatefulSet')
metadata: any()
spec:
  template:
    spec:
      containers: list(include('probes'))
---
probes:
  startupProbe: any( include('exec_command'), include('httpget') )
  livenessProbe: any( include('httpget'), include('exec_command') )
  readinessProbe: any( include('httpget'), include('exec_command') )
---
httpget:
  httpGet:
    path: str(required=False)
    port: any( str(), int())
  initialDelaySeconds: int()
  periodSeconds: int()
  successThreshold: int()
  timeoutSeconds: int()
  failureThreshold: int()
---
exec_command:
  exec:
    command: list(str())
  initialDelaySeconds: int()
  periodSeconds: int()
  successThreshold: int()
  timeoutSeconds: int()
  failureThreshold: int()
