{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.labels "context" $ ) | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    "helm.sh/resource-policy": keep 
spec:
  accessModes:
    {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.accessModes "context" $ ) | nindent 4 }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClass }}
  csi:
    {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.csi "context" $ ) | nindent 4 }}
  
{{- end -}}

