## Config map to insert a landing index.html page in the docker.  This may be removed later if the same is done while building the docker.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-index
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <title>Laning Page</title> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
    body, h1, h2, h3, h4, h5, h6  {
      font-family: "Trebuchet MS", Tahoma, sans-serif;
    }
    </style>
    <body>
    <header class="w3-container w3-teal">
      <div class="w3-padding">
        <img src="https://mosip.github.io/mosip-helm/mosip_logo.png" width="100px">
        <h1>MOSIP Deployment</h1>
        <h2><b>{{ .Values.landing.name }}</b></h2>
      </div>
    </header>
    <ul class="w3-ul w3-large w3-padding">
      <li><a href="https://{{ .Values.landing.activemq }}">ActiveMQ<a></li>
      <li><a href="https://{{ .Values.landing.admin }}">Admin<a></li>
      <li><a href="https://{{ .Values.landing.kafka }}">Kafka<a></li>
      <li><a href="https://{{ .Values.landing.keycloak }}">Keycloak<a></li>
      <li><a href="https://{{ .Values.landing.minio }}">MinIO<a></li>
      <li><a href="https://{{ .Values.landing.prereg }}/pre-registration-ui/">Pre-registration<a></li>
      <li><a href="https://{{ .Values.landing.regclient }}">Registration Client<a></li>
      <li>External API: <div class="w3-monospace">https://{{ .Values.landing.api }}</div></li>
      <li>Internal API: <div class="w3-monospace">https://{{ .Values.landing.apiInternal }}</div></li>
      <li>Postgres: <div class="w3-monospace">{{ .Values.landing.apiInternal}}:{{ .Values.landing.postgresPort}}</div></li>
    </ul>
    <footer class="w3-container w3-teal">
      <div class="w3-padding">
        <a href="https://mosip.io">MOSIP Website</a> &nbsp;&nbsp;&nbsp; 
        <a href="https://docs.mosip.io">MOSIP Docs</a>
      </div>
    </footer>
    </body>
    </html>
