{{- if .Values.databases.mosip_audit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-audit-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  db-audit-su-password: {{ .Values.databases.mosip_audit.suPassword | b64enc | quote }}
  db-audit-sysadmin-password: {{ .Values.databases.mosip_audit.sysadminPassword | b64enc | quote }}
  db-audit-dbadmin-password: {{ .Values.databases.mosip_audit.dbadminPassword | b64enc | quote }}
  db-audit-appadmin-password: {{ .Values.databases.mosip_audit.appadminPassword | b64enc | quote }}
  db-audit-dbuser-password: {{ .Values.databases.mosip_audit.dbuserPassword | b64enc | quote}}
{{- end }}
