apiVersion: v1
kind: Secret
metadata:
  name: db-common-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.dbUserPasswords.sysadminPassword }}
  db-sysadmin-password: {{ .Values.dbUserPasswords.sysadminPassword | b64enc | quote }}
  {{- else }}
  db-sysadmin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }} 

  {{- if  .Values.dbUserPasswords.dbadminPassword }}
  db-dbadmin-password: {{ .Values.dbUserPasswords.dbadminPassword | b64enc | quote }}
  {{- else }}
  db-dbadmin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }} 
  
  {{- if .Values.dbUserPasswords.appadminPassword }}
  db-appadmin-password: {{ .Values.dbUserPasswords.appadminPassword | b64enc | quote }}
  {{- else }}
  db-appadmin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }} 

  {{- if .Values.dbUserPasswords.dbuserPassword }}
  db-dbuser-password: {{ .Values.dbUserPasswords.dbuserPassword | b64enc | quote}}
  {{- else }}
  db-dbuser-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

