{{- if .Values.databases.mosip_regdevice.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-regdevice-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  db-regdevice-su-password: {{ .Values.databases.mosip_regdevice.suPassword | b64enc | quote }}
  db-regdevice-sysadmin-password: {{ .Values.databases.mosip_regdevice.sysadminPassword | b64enc | quote }}
  db-regdevice-dbadmin-password: {{ .Values.databases.mosip_regdevice.dbadminPassword | b64enc | quote }}
  db-regdevice-appadmin-password: {{ .Values.databases.mosip_regdevice.appadminPassword | b64enc | quote }}
  db-regdevice-dbuser-password: {{ .Values.databases.mosip_regdevice.dbuserPassword | b64enc | quote}}
{{- end }}
