apiVersion: v2
name: idp
description: A Helm chart for MOSIP idp module
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - idp
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP 
