apiVersion: v2
name: regproc-receiver
description: A Helm chart for MOSIP Registration Processor Packet Receiver stage
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - regproc-receiver
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP 
