{{ if .Values.debezium.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-deploy
  labels:
    app: debezium
spec:
  replicas: {{ .Values.debezium.replicaCount }}
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium-container
          image: {{ .Values.debezium.image }}
          env:
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.debezium.kafka.server }}
            - name: GROUP_ID
              value: {{ .Values.debezium.kafka.groupId | quote }}
            - name: OFFSET_STORAGE_TOPIC
              value: {{ .Values.debezium.kafka.topics.offset }}
            - name: CONFIG_STORAGE_TOPIC
              value: {{ .Values.debezium.kafka.topics.config }}
            - name: STATUS_STORAGE_TOPIC
              value: {{ .Values.debezium.kafka.topics.status }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
          - containerPort: {{ .Values.debezium.port }}
          {{- if .Values.debezium.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.debezium.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.debezium.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.debezium.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-service
  labels:
    app: debezium-service
spec:
  type: ClusterIP
  ports:
    - name: debezium
      protocol: TCP
      port: {{ .Values.debezium.port }}
  selector:
      app: debezium

{{ end }}
