apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never  # This is one time job
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: DB_PREFIX_INDEX
          value: {{ .Values.base.db_prefix }}
        - name: DB_HOSTNAME
          value: {{ .Values.base.db_hostname }}
        - name: DB_PORT
          value: {{ .Values.base.db_port }}
        - name: DB_USER
          value: {{ .Values.base.db_user }}
        - name: ES_URL
          value: {{ .Values.base.es_url }}
        - name: DB_PASS
          {{ if .Values.base.db_pass_direct }}
          value: {{ .Values.base.db_pass_direct }}
          {{ else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.base.db_pass_secretref.name }}
              key: {{ .Values.base.db_pass_secretref.key }}
          {{ end }}
        {{- range $key, $val := .Values.connectors_enabled }}
        - name: connector_{{ $key }}
          value: {{ $value | quote }}
        {{- end }}
