apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never  # This is one time job
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: DB_PREFIX_INDEX
          value: {{ .Values.base.db_prefix }}
        - name: DB_HOSTNAME
          value: {{ .Values.base.db_hostname }}
        - name: DB_PORT
          value: {{ .Values.base.db_port | quote }}
        - name: DB_USER
          value: {{ .Values.base.db_user }}
        - name: DB_PASS
          {{ if .Values.base.db_pass_direct }}
          value: {{ .Values.base.db_pass_direct }}
          {{ else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.base.db_pass_secretref.name }}
              key: {{ .Values.base.db_pass_secretref.key }}
          {{ end }}
        - name: ES_URL
          value: {{ .Values.base.es_url }}
        - name: KIBANA_URL
          value: {{ .Values.base.kibana_url }}
        {{ if .Values.base.is_connectors_enabled }}
        {{- range $key, $val := .Values.connectors_enabled }}
        - name: connector_{{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{ end }}
        {{ if .Values.base.is_kibana_enabled }}
        {{- range $key, $val := .Values.kibana_enabled }}
        - name: kibana_saved_object_{{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{ end }}
        volumeMounts:
        {{- range $key, $val := .Values.other_connectors }}
        {{ if $val }}
        - name: {{ $key }}
          mountPath: "/other_connectors/{{ $key }}"
        {{ end }}
        {{- end }}
        {{- range $key, $val := .Values.other_kibana }}
        {{ if $val }}
        - name: {{ $key }}
          mountPath: "/other_kibana_saved_objects/{{ $key }}"
        {{ end }}
        {{- end }}
      volumes:
      {{- range $key, $val := .Values.other_connectors }}
      {{ if $val }}
      - name: {{ $key }}
        configMap:
          name: {{ $key }}
      {{ end }}
      {{- end }}
      {{- range $key, $val := .Values.other_kibana }}
      {{ if $val }}
      - name: {{ $key }}
        configMap:
          name: {{ $key }}
      {{ end }}
      {{- end }}
