---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 8 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
  {{- end }}
data:
  {{- if .Values.apitestrig.configmaps.apitestrig }}
    {{- range $key, $value := .Values.apitestrig.configmaps.apitestrig }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 8 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
  {{- end }}
data:
  {{- if .Values.apitestrig.configmaps.s3 }}
  {{- range $key, $value := .Values.apitestrig.configmaps.s3 }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 8 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
  {{- end }}
data:
  {{- if .Values.apitestrig.configmaps.db }}
  {{- range $key, $value := .Values.apitestrig.configmaps.db }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}