kind: ServiceAccount
apiVersion: v1
metadata:
    name: sa-deployment-restart
    namespace: {{ .Release.Namespace }}
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: role-deployment-restart
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: ["apps", "extensions"]
      resources: ["deployments"]
      resourceNames: ["apitestrig-prereg"]
      verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
                                               # if you want to use `rollout status`
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: rb-deployment-restart
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: role-deployment-restart
subjects:
    - kind: ServiceAccount
      name: sa-deployment-restart
      namespace: {{ .Release.Namespace }}