apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak-init.fullname" . }}
  labels:
    {{- include "keycloak-init.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "keycloak-init.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak-init.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jobSecurityContext | nindent 8 }}
      restartPolicy: Never  # This is one time job
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- $globalSecretName := include "common.secrets.name" (dict "existingSecret" .Values.keycloak.existingSecret "context" $) }}
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloak.admin.secret.existingSecret }}
                key: {{ .Values.keycloak.admin.secret.key }}
          - name: KEYCLOAK_SERVER_URL
            valueFrom:
               configMapKeyRef:
                 name: {{ .Values.keycloak.host.existingConfigMap }} 
                 key:  {{ .Values.keycloak.host.key }} 
          - name: KEYCLOAK_ADMIN_USER
            valueFrom:
               configMapKeyRef:
                 name: {{ .Values.keycloak.admin.userName.existingConfigMap }} 
                 key:  {{ .Values.keycloak.admin.userName.key }} 
          envFrom:
              - secretRef:
                  name: keycloak-client-secrets

          volumeMounts:
            - name: keycloak-init-input
              mountPath: /opt/mosip/input/input.yaml
              subPath: input.yaml
      volumes:
        - name: keycloak-init-input
          configMap:
            name: {{ printf "%s-configuration" (include "keycloak-init.fullname" .) }}

