apiVersion: v2
name: mosip-file-server
description: A Helm chart to installed Downloader for mosip-file-server Application
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies: 
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - mosip-file-server
  - fileserver
maintainers:
  - email: info@mosip.io
    name: MOSIP 
