replicaCount: 1

nginx:
  image: nginx:latest
  imagePullPolicy: IfNotPresent

scriptRunner:
  image: alpine:latest
  imagePullPolicy: IfNotPresent


## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##
startupProbe:
  enabled: true
  httpGet:
    path: "/"
    port: 80
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

livenessProbe:
  enabled: true
  httpGet:
    path: "/"
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: "/"
    port: 80
  initialDelaySeconds: 0
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 1500Mi
  requests:
    cpu: 100m
    memory: 1500Mi

istio:
  enabled: true
  gateways:
    - istio-system/internal
  prefix: /deployment-info
  rewrite: /deployment_info/deployment_info.txt
