name: Publish mosip-helm charts for a Release

# Triggered when code is pushed to any branch in a repository
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Trigger Publish Helm Charts'
        required: false
        default: 'Helm Chart Publishing'
      git-ref:
        description: 'tag to publish helm chart'
        required: true

jobs:
  Generate_Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Repository
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Setup Branch and Env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=${{ github.event.inputs.git-ref }}" >> $GITHUB_ENV

      - name: Generate tar files
        run: |
          helm repo add mosip https://mosip.github.io/mosip-helm
          cd charts &&
          find * -prune -type d > ../tmp.txt
          cd ..
          while IFS= read -r line
          do
            fullpath=$line
            echo "Pullpath: $fullpath"
            fullname=$(basename "$line")
            echo "Filename: $fullname"
            helm package charts/$fullpath
          done < tmp.txt

      - name: Upload tar as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: charts
          path: ./*.tgz
          retention-days: 1

      - name: Checkout branch for publishing
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download tar from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: charts
          path: ./

      - name: Commit Changes to mosip-helm Repository
        uses: EndBug/add-and-commit@v7
        with:
          branch: gh-pages
          default_author: github_actions
          message: 'added helm charts for release ${{ github.event.inputs.git-ref }}'
          add: './*.tgz'
